### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Titu-beep** [jaikeerthick/Easy-Attendance-App#1]
Please reply

**Comment by jaikeerthick** [comment]
Hi. How can I help you?

**Comment by Titu-beep** [comment]
can you help me with SQLite as database

**Comment by jaikeerthick** [comment]
Sorry this project is for showing how easy Realm database is. You can use SQLITE for CRUD operations to replace Realm

**Comment by Titu-beep** [comment]
This application is made by you .. right..

then can I use sqlite instead for this... instead of realm database

**Comment by Titu-beep** [comment]
Or... IF you any respo.... which has attendance management system application.. with SQLite database...
Please suggest me

**Comment by jaikeerthick** [comment]
Yeah for sure you can! You can use it for any commercial or noncommercial purposes. Altering it to the end. No issues on that 🐱

**Comment by Titu-beep** [comment]
I am using this for my college projects

**Comment by jaikeerthick** [comment]
Great 👍
