### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Krishnatejamarisetty** [jaikeerthick/Easy-Attendance-App#6]
Im unable to download the source code

**Comment by jaikeerthick** [comment]
Can you be more specific please?

**Comment by SarthakTeli18** [comment]
Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @5e69b7bd
i am getting this kind of error

**Comment by Krishnatejamarisetty** [comment]
Hii the code isn't running on Android studio. 
It's saying that it contain errors.
Can you please tell me what to do

**Comment by Saipradeepedara** [comment]
yess same problem.
could you please tell me im running on android studio but not giving any output

**Comment by jaikeerthick** [comment]
Closing as the error is not specifically mentioned. Open new issue with specific error logs
